# SPDX-License-Identifier: GPL-2.0
rockchip-hdmirx-class-objs := rk_hdmirx_class.o
rockchip-hdmirx-objs := rk_hdmirx.o rk_hdmirx_cec.o rk_hdmirx_hdcp.o rk_hdmirx_audio.o rk_hdmirx_video.o

obj-$(CONFIG_VIDEO_ROCKCHIP_HDMIRX_CLASS) += rockchip-hdmirx-class.o
obj-$(CONFIG_VIDEO_ROCKCHIP_HDMIRX) += rockchip-hdmirx.o
